create table teachers(
    id integer primary key generated by default as identity, 
    username text not null, 
    password text not null, 
    fullname text, 
    "language" text 
);

create table students(
    id integer primary key generated by default as identity, 
    username text not null, 
    password text not null, 
    fullname text 
);