create type role as enum(
    'student', 
    'teacher'
);

create table users(
    id integer primary key generated by default as identity, 
    username text not null, 
    password text not null, 
    fullname text, 
    language integer not null references languages(id) on delete cascade, 
    role role
);
