create table questions(
    id integer primary key generated by default as identity, 
    quiz_id integer not null references quiz(id) on delete cascade, 
    title text, 
    answers text[], 
    correct_answer integer
);