create table quizzes(
    id integer primary key generated by default as identity, 
    title text not null,
    teacher_id integer not null references users(id) on delete cascade, 
    setup text, 
    finished boolean default false
);