create table questions(
    id integer primary key generated by default as identity, 
    quiz_id integer not null references quizzes(id) on delete cascade, 
    title text not null, 
    answers text[] not null, 
    correct_answers integer[] not null, 
    value integer
);