create table student_quiz_rel(
    id integer primary key generated by default as identity, 
    quiz_id integer not null references quiz(id) on delete cascade, 
    student_id integer not null references students(id) on delete cascade, 
    score integer
);