create table student_quiz_rels(
    id integer primary key generated by default as identity, 
    quiz_id integer not null references quizzes(id) on delete cascade, 
    student_id integer not null references users(id) on delete cascade, 
    score integer not null
);