truncate languages, users, quizzes, questions, student_quiz_rels, teacher_lang_rels;

insert into languages(title) values
('Areare'),
('Auhelawa'),
('ATong'),
('Aari'),
('Abanyom'),
('Abaza'),
('Abkhaz'),
('Abujmaria'),
('Acehnese'),
('Adamorobe Sign Language'),
('Adele'),
('Adyghe'),
('Afar'),
('Afrikaans'),
('Afro-Seminole Creole'),
('Aimaq'),
('Aini'),
('Ainu'),
('Akan'),
('Akawaio'),
('Aklanon'),
('Albanian'),
('Aleut'),
('Algonquin'),
('Alsatian'),
('Altay'),
('Alutor'),
('American Sign Language'),
('Amharic'),
('Anda'),
('Amdang'),
('Angika'),
('Anyin'),
('Ao'),
('A-Pucikwar'),
('Arabic'),
('Aragonese'),
('Aramaic'),
('Are'),
('Argobba'),
('Aromanian'),
('Armenian'),
('Arvanitic'),
('Ashkun'),
('Assamese'),
('Assyrian Neo-Aramaic'),
('Ateso'),
('Asi'),
('Asturian'),
('Auslan'),
('Austro-Bavarian'),
('Avar'),
('Avestan'),
('Awadhi'),
('Aymara'),
('Azerbaijani'),
('Badaga'),
('Badeshi'),
('Bahnar'),
('Balinese'),
('Balochi'),
('Balti'),
('Bambara'),
('Banjar'),
('Banyumasan'),
('Bartangi'),
('Basaa'),
('Bashkardi'),
('Bashkir'),
('Basque'),
('Batak Karo'),
('Batak Toba'),
('Bats'),
('Beja'),
('Belarusian'),
('Belhare'),
('Berta'),
('Bemba'),
('Bengali'),
('Bezhta'),
('Betawi'),
('Bete'),
('Bhili'),
('Bhojpuri'),
('Bijil Neo-Aramaic'),
('Bikol'),
('Bikya'),
('Bissa'),
('Blackfoot'),
('Boholano'),
('Bohtan Neo-Aramaic'),
('Bonan'),
('Bororo'),
('Bodo'),
('Bosnian'),
('Brahui'),
('Breton'),
('British Sign Language'),
('Bua'),
('Buginese'),
('Bukusu'),
('Bulgarian'),
('Bunjevac'),
('Burmese'),
('Burushaski'),
('Buryat'),
('Caluyanon'),
('Cantonese'),
('Catalan'),
('Cayuga'),
('Cebuano'),
('Chabacano'),
('Chaga'),
('Chakma'),
('Chaldean Neo-Aramaic'),
('Chamorro'),
('Chaouia'),
('Chechen'),
('Chenchu'),
('Chenoua'),
('Cherokee'),
('Cheyenne'),
('Chhattisgarhi'),
('Chickasaw'),
('Chintang'),
('Chilcotin'),
('Chinese'),
('Chiricahua'),
('Chichewa'),
('Chipewyan'),
('Chittagonian'),
('Choctaw'),
('Chorasmian'),
('Chukchi'),
('Chulym'),
('Church Slavonic'),
('Chuukese'),
('Chuvash'),
('Cocoma'),
('Cocopa'),
('Coeur d’Alene'),
('Comanche'),
('Comorian'),
('Cornish '),
('Corsican'),
('Cree'),
('Crimean Tatar'),
('Croatian'),
('Cuyonon'),
('Czech'),
('Dagbani'),
('Dahlik'),
('Dalecarlian'),
('Dameli'),
('Danish'),
('Dargin'),
('Dari '),
('Dari-Persian'),
('Daur'),
('Denaina'),
('Dhatki'),
('Dhivehi'),
('Dida'),
('Dioula'),
('Dogri'),
('Dogrib'),
('Dolgan'),
('Domaaki'),
('Dongxiang'),
('Duala'),
('Dungan'),
('Dutch'),
('Dzhidi'),
('Dzongkha'),
('Eastern Yugur'),
('Egyptian Arabic'),
('Ekoti'),
('Enets'),
('English'),
('Erzya'),
('Esperanto'),
('Estonian'),
('Even'),
('Evenk'),
('Ewe'),
('Extremaduran'),
('Faeroese'),
('Fang'),
('Fijian'),
('Filipino'),
('Finnish'),
('Finnish Sign Language'),
('Flemish language'),
('Fon'),
('Franco-Provençal'),
('French'),
('French Sign Language'),
('Frisian), North'),
('Frisian), Saterland'),
('Frisian), West'),
('Friulian'),
('Fula'),
('Fur'),
('Ga'),
('Gadaba'),
('Gagauz'),
('Galician'),
('Gan'),
('Ganda'),
('Gangte'),
('Garhwali'),
('Gayo'),
('Gen ẽ'),
('Georgian'),
('German'),
('German Sign Language'),
('Gikuyu'),
('Gilbertese'),
('Gileki'),
('Goaria'),
('Gondi'),
('Gorani'),
('Gawar-Bati'),
('Greek'),
('Guaraní'),
('Guinea-Bissau Creole'),
('Gujarati'),
('Gula Iro'),
('Gullah'),
('Gusii'),
('Gwichʼin'),
('Hadza'),
('Haida (Na-Dené)
(Haitian Creole'),
('Hakka'),
('Hän'),
('Harari'),
('Harauti'),
('Harsusi'),
('Haryanavi '),
('Harzani'),
('Hausa'),
('Havasupai'),
('Hawaiian'),
('Hawaii Pidgin Sign Language'),
('Hazaragi '),
('Hebrew'),
('Herero'),
('Hértevin'),
('Hiligaynon'),
('Hindi'),
('Hinukh'),
('Hiri Motu'),
('Hixkaryana'),
('Hmong'),
('Ho'),
('Hobyót'),
('Hopi'),
('Hulaulá'),
('Hungarian'),
('Hutterite German'),
('Ibibio'),
('Iban'),
('Ibanag'),
('Icelandic'),
('Ido'),
('Ifè'),
('Igbo'),
('Ikalanga'),
('Ili Turki'),
('Ilokano'),
('Inari Sami'),
('Indonesian'),
('Ingrian'),
('Ingush'),
('Interlingua'),
('Inuktitut'),
('Inupiaq'),
('Inuvialuktun'),
('Iraqw'),
('Irish'),
('Irish Sign Language'),
('Irula'),
('Isan'),
('Ishkashimi'),
('Istro-Romanian'),
('Italian'),
('Itelmen'),
('Jacaltec'),
('Jalaa (unclassified), possibly Niger–Congo)
(Japanese'),
('Jaqaru'),
('Jarai'),
('Javanese'),
('Jibbali'),
('Jewish Babylonian Aramaic'),
('Jicarilla Apache'),
('Juang'),
('Jurchen'),
('Kabardian'),
('Kabyle'),
('Kachin'),
('Kalaallisut'),
('Kalami'),
('Kalasha'),
('Kalmyk'),
('Kalto'),
('Kankanai'),
('Kannada'),
('Kaonde'),
('Kapampangan'),
('Karachay-Balkar'),
('Karagas'),
('Karaim'),
('Karakalpak'),
('Karelian'),
('Kashmiri'),
('Kashubian'),
('Kazakh'),
('Kerek'),
('Ket'),
('Khakas'),
('Khalaj'),
('Kham'),
('Khandeshi'),
('Khanty'),
('Khasi'),
('Khitan'),
('Khmer'),
('Khmu'),
('Khowar'),
('Kildin Sami'),
('Kimatuumbi'),
('Kinaray-a'),
('Kinyarwanda'),
('Kirombo'),
('Kirundi'),
('Kivunjo'),
('Klallam'),
('Kodava Takk'),
('Kohistani'),
('Kolami'),
('Komi'),
('Konkani'),
('Kongo'),
('Koraga'),
('Korandje'),
('Korean'),
('Korku'),
('Korowai (Trans–New Guinea)
(Korwa'),
('Koryak'),
('Kosraean'),
('Kota'),
('Koyra Chiini'),
('Koy Sanjaq Surat'),
('Koya'),
('Krymchak'),
('Kujarge (unclassified), perhaps Chadic)
(Kui'),
('Kumauni'),
('Kumyk'),
('Kumzari'),
('ǃKung'),
('Kurdish'),
('Kurukh'),
('Kusunda'),
('Kutenai'),
('Kwanyama'),
('Kxoe'),
('Kyrgyz'),
('Laal'),
('Ladakhi'),
('Ladin'),
('Ladino'),
('Laki'),
('Lakota'),
('Lambadi'),
('Lao'),
('Larestani'),
('Latin '),
('Latvian'),
('Laz'),
('Leonese'),
('Lezgi'),
('Ligbi'),
('Limburgish'),
('Lingala'),
('Lipan Apache'),
('Lisan al-Dawat'),
('Lishana Deni'),
('Lishanid Noshan'),
('Lithuanian'),
('Livonian'),
('Lombard'),
('Lotha'),
('Low German'),
('Lower Sorbian'),
('Lozi'),
('Ludic'),
('Lunda'),
('Luo'),
('Luri'),
('Lushootseed'),
('Lusoga'),
('Luvale'),
('Luwati'),
('Luxembourgish'),
('Macedonian'),
('Magadhi'),
('Maguindanao'),
('Maithili'),
('Makasar'),
('Makhuwa'),
('Makhuwa-Meetto'),
('Malagasy'),
('Malay'),
('Malayalam'),
('Malaysian Sign Language'),
('Maltese'),
('Malto'),
('Malvi'),
('Mam'),
('Manchu'),
('Mandaic'),
('Mandarin'),
('Mandinka'),
('Mansi'),
('Manx'),
('Manyika'),
('Maori'),
('Mapudungun'),
('Maranao'),
('Marathi'),
('Mari'),
('Maria'),
('Marquesan'),
('Marshallese'),
('Marthas Vineyard Sign Language'),
('Masaba'),
('Masbatenyo (Malayo-Polynesian
(Meitei'),
('Mauritian Creole'),
('Maya'),
('Mazandarani'),
('Meänkieli'),
('Megleno-Romanian'),
('Megrelian'),
('Mehri'),
('Menominee'),
('Mentawai'),
('Meroitic (unclassified), maybe Nilo-Saharan )
(Mescalero Apache'),
('Meru'),
('Michif (mixed), French and Cree based)
(Mikasuki'),
('Mikmaq'),
('Minangkabau'),
('Mirandese'),
('Mobilian Jargon (pidgin), Choctaw and French based)
(Moghol'),
('Mohawk'),
('Moksha'),
('Molengue'),
('Mon'),
('Mongolian'),
('Mono'),
('Mono'),
('Mono'),
('Montagnais'),
('Montenegrin'),
('Motu'),
('Muher'),
('Mundari'),
('Munji'),
('Muria'),
('Nafaanra'),
('Nagarchal'),
('Nahuatl'),
('Nama'),
('Nanai'),
('Nauruan'),
('Navajo (Na-Dené)
(Ndau'),
('Ndebele'),
('Ndonga'),
('Neapolitan'),
('Negidal'),
('Nepal Bhasa'),
('Nepali'),
('New Zealand Sign Language'),
('Nihali'),
('Nganasan'),
('Ngumba'),
('Nheengatu í'),
('Nias
(Nicaraguan Sign Language'),
('Niellim'),
('Nigerian Pidgin (pidgin), English-based)
(Nisenan '),
('Niuean'),
('Nivkh'),
('Nogai'),
('Norfuk (cant), English-Tahitian based)
(Norman'),
('Northern Sami'),
('Northern Sotho'),
('Northern Straits Salish)'),
('Northern Yukaghir'),
('Norwegian (Bokmål), Nynorsk), Riksmål)'),
('Nuer'),
('Nuxálk'),
('Nyabwa'),
('Nyah Kur'),
('Nyangumarta'),
('Nyoro'),
('Nǀu'),
('Occitan çal'),
('Ojibwe'),
('Okinawan'),
('Olonets Karelian'),
('Omagua'),
('Ongota'),
('Oriya'),
('Ormuri'),
('Oroch'),
('Orok'),
('Oromo'),
('Ossetic'),
('Páez'),
('Palauan'),
('Pangasinan'),
('Papiamento'),
('Parachi'),
('Parya'),
('Pashto'),
('Pennsylvania Dutch'),
('Persian ), as it is referred to in the Persian language'),
('Phalura'),
('Phuthi'),
('Picard'),
('Pirahã'),
('Plautdietsch'),
('Polish'),
('Portuguese'),
('Pothohari'),
('Pradhan'),
('Puelche'),
('Puma'),
('Punjabi'),
('Qashqai'),
('Quebec Sign Language'),
('Rajasthani'),
('Ratagnon'),
('Réunion Creole'),
('Romanian'),
('Romansh'),
('Romany'),
('Romblomanon'),
('Rotokas'),
('Runyankole language'),
('Russian'),
('Russian Sign Language'),
('Ruthenian'),
('Salar'),
('Samoan'),
('Sandawe'),
('Sango'),
('Sanskrit '),
('Santali'),
('Sara'),
('Saraiki'),
('Saramaccan'),
('Sardinian'),
('Sarikoli'),
('Standard Arabic'),
('Saurashtra'),
('Savara'),
('Savi'),
('Sawai'),
('Scots'),
('Scots Gaelic'),
('Selang
(Selkup'),
('Semnani'),
('Senaya'),
('Serbian'),
('Serbo-Croatian'),
('Sesotho'),
('Seto'),
('Seychellois Creole'),
('Shimaore'),
('Shina'),
('Shona'),
('Shor'),
('Shoshoni'),
('Shughni'),
('Shumashti'),
('Shuswap'),
('Sicilian'),
('Sidamo'),
('Sika'),
('Silesian'),
('Silte'),
('Sindhi'),
('Sinhalese'),
('Sioux'),
('Sivandi'),
('Skolt Sami'),
('Slavey'),
('Slovak'),
('Slovene'),
('Soddo'),
('Somali'),
('Sonjo'),
('Sonsorolese'),
('Soqotri'),
('Sora'),
('Sorbian), Lower'),
('Sorbian), Upper'),
('Sourashtra'),
('Southern Sami'),
('South Estonian'),
('Southern Yukaghir'),
('Spanish'),
('Sranan Tongo'),
('Stat imcets'),
('Sucite ìcìté Sénoufo'),
('Suba'),
('Sundanese'),
('Supyire'),
('Surigaonon'),
('Susu'),
('Svan'),
('Swahili'),
('Swati'),
('Swedish'),
('Syriac'),
('Tabasaran'),
('Tachelhit'),
('Tagalog'),
('Tahitian'),
('Taiwanese Sign Language'),
('Tajik'),
('Takestani'),
('Talysh'),
('Tamil'),
('Tanacross'),
('Tangut'),
('Tarifit'),
('Tat'),
('Tatar'),
('Tausug'),
('Tehuelche'),
('Telugu'),
('Tetum'),
('Tepehua language'),
('Tepehuán language'),
('Thai'),
('Tharu'),
('Tibetan'),
('Tigre'),
('Tigrinya'),
('Timbisha'),
('Tiv'),
('Tlingit (Na-Dené)
(Tobian'),
('Toda'),
('Tok Pisin'),
('Tokelauan'),
('Tonga'),
('Tongan'),
('Torwali'),
('Tregami'),
('Tsat'),
('Tsez'),
('Tshiluba'),
('Tsonga'),
('Tswana'),
('Tu'),
('Tuareg languages'),
('Tulu'),
('Tumbuka'),
('Tupiniquim'),
('Turkish'),
('Turkmen'),
('Turoyo'),
('Tuvaluan'),
('Tuvan Tuvin'),
('Udihe'),
('Udmurt'),
('Ukrainian'),
('Ukwuani-Aboh-Ndoni'),
('Ulch'),
('Unserdeutsch'),
('Upper Sorbian'),
('Urdu'),
('Uripiv'),
('Urum'),
('Ute'),
('Uyghur'),
('Uzbek'),
('Vafsi'),
('Valencian'),
('Valencian Sign Language'),
('Vasi-vari'),
('Venda'),
('Venetian'),
('Veps'),
('Vietnamese'),
('Võro'),
('Votic'),
('Waddar'),
('Waigali'),
('Waima'),
('Wakhi'),
('Walloon'),
('Waray-Waray'),
('Washo'),
('Welsh'),
('Western Neo-Aramaic'),
('Wolane (Silte)'),
('Wolof'),
('Wu'),
('Xhosa'),
('Xiang'),
('Xibe'),
('Xipaya'),
('ǃXóõ'),
('Yaaku language'),
('Yaeyama language'),
('Yaghnobi'),
('Yakut'),
('Yankunytjatjara language'),
('Yanomami'),
('Yanyuwa'),
('Yapese'),
('Yaqui'),
('Yauma'),
('Yavapai'),
('Yazdi'),
('Yazgulyam'),
('Yemenite Hebrew'),
('Yeni language'),
('Yevanic language'),
('Yi language'),
('Yiddish'),
('Yidgha'),
('Yogur (also known as Yoghur),  Sarï Uyghur), and  Yellow Uyghur), Mongolic'),
('Yokutsan languages'),
('Yonaguni language'),
('Yorùbá language'),
('Yucatec Maya language'),
('Yucatec Maya Sign Language'),
('Yuchi language'),
('Yugur'),
('Yukaghir languages'),
('Yupik language'),
('Yurats language'),
('Yurok language'),
('Záparo'),
('Zapotec'),
('Zazaki'),
('Zulu '),
('Zuñi'),
('Zway');